# Generated by Django 2.2.6 on 2020-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhapp', '0002_auto_20200303_1512'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nikename',
            new_name='nickname',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname', 'openid'], name='name'),
        ),
    ]
